jan_martyrs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views
from martyrs.views import MartyrsListView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', MartyrsListView.as_view(), name='home'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^martyrs/', include('martyrs.urls', namespace='martyrs')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

martyrs/urls.py
from django.conf.urls import url
from martyrs import views


urlpatterns = [
    url(r'^new/$', views.MartyrsCreateView.as_view(), name='create'),
    url(r'^$', views.MartyrsListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.MartyrsDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update/$', views.MartyrsUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', views.MartyrsDeleteView.as_view(), name='delete'),
]

martyrs/models.py
from django.utils.translation import ugettext_lazy as _
from django.utils.encoding import python_2_unicode_compatible
from django.db import models


@python_2_unicode_compatible
class Martyr(models.Model):
    name = models.CharField(_('Name'), max_length=255)
    birth_date = models.DateField(_('Date of birth'))
    death_date = models.DateField(_('Date of death'))
    death_cause = models.TextField(_('Cause of death'))
    officer_name = models.CharField(_('Officer\'s name'), max_length=255, null=True, blank=True)
    governorate = models.CharField(_('Governorate'), max_length=100)

    created_at = models.DateTimeField(auto_now_add=True)
    last_update = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = _("Martyr")
        verbose_name_plural = _("Martyrs")

    def __str__(self):
        return u"Martyr: %s" % self.name

martyrs/forms.py
from django import forms
from martyrs.models import Martyr


class MartyrForm(forms.ModelForm):
    class Meta:
        model = Martyr
        fields = ('name', 'birth_date', 'death_date', 'death_cause', 'officer_name', 'governorate',)

martyrs/views.py
from django.views.generic import (ListView, DetailView, CreateView, UpdateView,
                                  DeleteView)
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.urlresolvers import reverse
from martyrs.models import Martyr
from martyrs.forms import MartyrForm


class LoginRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)


class MartyrsCreateView(LoginRequiredMixin, CreateView):
    model = Martyr
    template_name = 'martyrs/create.html'
    form_class = MartyrForm

    def get_success_url(self):
        """redirect to martyr page on success"""
        return reverse('martyrs:detail', kwargs={'pk': self.object.pk})


class MartyrsListView(ListView):
    model = Martyr
    template_name = 'martyrs/list.html'


class MartyrsDetailView(DetailView):
    model = Martyr
    template_name = 'martyrs/detail.html'


class MartyrsUpdateView(LoginRequiredMixin, UpdateView):
    model = Martyr
    template_name = 'martyrs/update.html'
    form_class = MartyrForm

    def get_success_url(self):
        """redirect to martyr page on success"""
        return reverse('martyrs:detail', kwargs={'pk': self.object.pk})


class MartyrsDeleteView(LoginRequiredMixin, DeleteView):
    model = Martyr
    template_name = 'martyrs/delete.html'

    def get_success_url(self):
        """redirect to martyr list on success"""
        return reverse('martyrs:list')

martyrs/templates/martyrs/create.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %}
  {% trans "Add Martyr" %} | {% trans "Martyrs" %}
{% endblock title %}

{% block extraheader %}
  <link href="{% static "css/bootstrap-datepicker3.min.css" %}" rel="stylesheet">
{% endblock extraheader %}

{% block body %}
  <h2>{% blocktrans %}
      Do you know a #Jan25 Martyr?
      Tell us about hime
  {% endblocktrans %}</h2>
  {% include "martyrs/form.html" %}
{% endblock body %}

{% block footerjs %}
  <script type="text/javascript" src="{% static "js/bootstrap-datepicker.min.js" %}"></script>
  <script type="text/javascript">
    $(document).ready(function () {
      $('#id_birth_date').datepicker({format: 'yyyy-mm-dd', weekStart: -1});
      $('#id_death_date').datepicker({format: 'yyyy-mm-dd', weekStart: -1});
    })
  </script>
{% endblock footerjs %}

martyrs/templates/martyrs/delete.html
{% extends "base.html" %}
{% load i18n %}

{% block body %}
  {% blocktrans with name=martyr.name %}
      Are you sure you want to delete {{ name }}?
  {% endblocktrans %}
  <form method="POST" action=".">{% csrf_token %}
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
      </div>
    </div>

  </form>
{% endblock body %}

martyrs/templates/martyrs/detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
  {% trans "Martyr" %} {{ martyr.name }} | {% trans "Martyrs" %}
{% endblock title %}

{% block body %}
    {% include "martyrs/martyr.html" %}

  {% if user.is_authenticated %}
    <a class="btn btn-primary" id="backBtn" href="{% url "martyrs:list" %}">{% trans "Back" %}</a>
    <a class="btn btn-warning" id="backBtn" href="{% url "martyrs:update" pk=martyr.pk %}">{% trans "Update" %}</a>
    <a class="btn btn-danger" id="backBtn" href="{% url "martyrs:delete" pk=martyr.pk %}">{% trans "Delete" %}</a>
  {% endif %}
{% endblock body %}

martyrs/templates/martyrs/form.html
{% load widget_tweaks i18n %}

<form action="." method="POST" class="form-horizontal">{% csrf_token %}
  {{ form.non_field_errors }}
  {% for field in form %}
    <div class="form-group">
      {{ field.errors }}
      <label for="id_{{ field.name }}" class="col-sm-2 control-label">{{ field.label }}</label>
      <div class="col-sm-10">
        {% render_field field class="form-control" placeholder=field.label %}
      </div>
    </div>
  {% endfor %}
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">{% trans "Submit" %}</button>
    </div>
  </div>
</form>

martyrs/templates/martyrs/list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
  {% trans "Martyrs List" %} | {% trans "Martyrs" %}
{% endblock title %}

{% block body %}
  {% if user.is_authenticated %}
    <a href="{% url "martyrs:create" %}" class="btn btn-success">{% trans "Add new Martyr!" %}</a>
  {% endif %}
  {% for martyr in martyr_list %}
    {% include "martyrs/martyr.html" %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock body %}

martyrs/templates/martyrs/martyr.html
{% load i18n %}
<div class="row">
  <br>
  <div class="col-md-12">
    <h3><a href="{% url "martyrs:detail" pk=martyr.pk %}">{{ martyr.name }}</a></h3>
    <div class="row">
      <div class="martyr-detail col-xs-9">
        <p>{% trans "Birth Date" %}: {{ martyr.birth_date }}</p>
        <p>{% trans "Death Date" %}: {{ martyr.death_date }}</p>
        <p>{% trans "Cause of Death" %}: {{ martyr.death_cause }}</p>
        <p>{% trans "Officer's Name" %}: {{ martyr.officer_name }}</p>
        <p>{% trans "Governorate" %}: {{ martyr.governorate }}</p>
      </div>
    </div>
  </div>
</div>

martyrs/templates/martyrs/update.html
{% extends "base.html" %}
{% load i18n static %}

{% block title %}
  {% blocktrans with name=martyr.name %}
      Update {{ name }} Profile.
  {% endblocktrans %} | {% trans "Martyrs" %}
{% endblock title %}

{% block extraheader %}
  <link href="{% static "css/bootstrap-datepicker3.min.css" %}" rel="stylesheet">
{% endblock extraheader %}

{% block body %}
  <h2>{% blocktrans with name=martyr.name %}
      Update {{ name }} Profile.
  {% endblocktrans %}</h2>
  {% include "martyrs/form.html" %}
{% endblock body %}

{% block footerjs %}
  <script type="text/javascript" src="{% static "js/bootstrap-datepicker.min.js" %}"></script>
  <script type="text/javascript">
    $(document).ready(function () {
      $('#id_birth_date').datepicker({format: 'yyyy-mm-dd', weekStart: 6});
      $('#id_death_date').datepicker({format: 'yyyy-mm-dd', weekStart: 6});
    })
  </script>
{% endblock footerjs %}

templates/base.html
{% load static i18n %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>{% block title %}{% trans "Martyrs" %}{% endblock title %}</title>
    <meta name="generator" content="Bootply" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link href="{% static "css/styles.css" %}" rel="stylesheet">
    {% block extraheader %}{% endblock extraheader %}
  </head>
  <body>
<header class="navbar navbar-bright navbar-fixed-top" role="banner">
  <div class="container">
    <div class="navbar-header col-xs-12">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="{% url "home" %}" class="navbar-brand">{% trans "Home" %}</a>
      {% if user.is_authenticated %}
        <a class="pull-right auth-link" href="{% url "logout" %}">{% trans "Signout" %}</a>
      {% else %}
        <a class="pull-right auth-link" href="{% url "login" %}">{% trans "Signin" %}</a>
      {% endif %}
    </div>
  </div>
</header>

<div id="masthead">  
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1>{% trans "#Jan25 Martyrs" %}
          <p class="lead"></p>
        </h1>
      </div>
      <div class="col-md-5">
        <div class="well well-lg"> 
          <div class="row">
            <div class="col-sm-12">
              
      
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div><!-- /cont -->
  
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="top-spacer"> </div>
      </div>
    </div> 
  </div><!-- /cont -->
  
</div>


<div class="container">
  <div class="row">
    
    <div class="col-md-12"> 
      
      <div class="panel">
        <div class="panel-body">
        {% block body %}{% endblock body %}


        </div>
      </div>
    </div><!--/col-12-->
  </div>
</div>

<hr>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-6">
        <ul class="list-inline">
          <li><i class="icon-facebook icon-2x"></i></li>
          <li><i class="icon-twitter icon-2x"></i></li>
          <li><i class="icon-google-plus icon-2x"></i></li>
          <li><i class="icon-pinterest icon-2x"></i></li>
        </ul>
        
      </div>
      <div class="col-sm-6">
          <p class="pull-right">God's mercy on the martyrs. <i class="icon-heart-empty"></i></p>
      </div>
    </div>
  </div>
</footer>
  <!-- script references -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    {% block footerjs %}{% endblock footerjs %}
  </body>
</html>